//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComment
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public int PostId { get; set; }
        public Nullable<int> Author { get; set; }
        public System.DateTime Date { get; set; }
    }
}
